services:
  web:
    build:
      context: ../apps/web
      dockerfile: ../docker/web/Dockerfile
    env_file:
      - ../apps/web/.env
    ports:
      - "4000:80" # ホストの3000ポートをコンテナの80ポートにマッピング
    volumes:
      - ../apps/web:/app
      - /app/node_modules:/app/node_modules
